matrix_formats ?=
include $(matrix_formats)../../../makefile.in

F90INCLUDE ?= $(matrix_formats)../../../include

matrix_format_targets = $(matrix_formats)csr.o $(matrix_formats)bsr.o $(matrix_formats)ellpack.o
