#!/usr/bin/env python

env = Environment(
    tools=['default','gfortran'],
    F90='gfortran',
    LINK='gfortran',
    FORTRANMODDIR='#/include',
    FORTRANMODDIRPREFIX='-J',
    F90PATH=['#/include','/usr/local/include'])

bvp_sources = Split("""bvp.f90""")

libsforbvp = Split("""linalg mesh fem netcdf netcdff blas lapack""")
libpathforbvp = Split("""/usr/local/lib #/src/linalg #/src/mesh #/src/fem""")

env.Program('bvp',bvp_sources, LIBS=libsforbvp, LIBPATH=libpathforbvp)
