#!/usr/bin/env python

Import('masterEnv')
env = masterEnv.Clone(F90PATH=['#/include','/usr/include','/usr/local/include'])

bvp_sources = Split("""bvp.f90""")
poisson_sources = Split("""poisson.f90""")
permutations_sources = Split("""permutations.f90""")

libsforbvp = Split("""linalg mesh fem netcdf netcdff blas lapack gomp""")
libpathforbvp = Split("""/usr/local/lib #/src/linalg #/src/mesh #/src/fem""")

env.Program('bvp',bvp_sources, LIBS=libsforbvp, LIBPATH=libpathforbvp)

env.Program('poisson',poisson_sources,LIBS=libsforbvp,LIBPATH=libpathforbvp)

env.Program('permutations',permutations_sources,LIBS=libsforbvp,LIBPATH=libpathforbvp)
