#!/usr/bin/env python

env = Environment(
    tools=['default','gfortran'],
    F90='gfortran',
    LINK='gfortran',
    FORTRANMODDIR='#/include',
    FORTRANMODDIRPREFIX='-J',
    F90PATH='#/include')

fem_sources = Split("""fem_mod.f90""")

femlib = env.Library('fem',fem_sources, LIBS=['mesh','linalg'], LIBPATH=['../mesh','../linalg'])
#env.Alias('install',env.Install('../../lib',femlib))
