#!/usr/bin/env python

env = Environment(
    tools=['default','gfortran'],
    F90='gfortran',
    LINK='gfortran',
    FORTRANMODDIR='#/include',
    FORTRANMODDIRPREFIX='-J',
    F90PATH='#/include')

mesh_sources = Split("""meshes.f90""")

meshlib = env.Library('meshes',mesh_sources)
#env.Alias('install', env.Install('../../lib',meshlib))

