#!/usr/bin/env python

Import('masterEnv')
env = masterEnv.Clone(F90FLAGS='-fbounds-check -g -fopenmp')

linalg_sources = Split("""sparse_matrix_mod.f90 
                            csr_matrix_mod.f90
                            bsr_matrix_mod.f90
                            permutation_mod.f90
                            iterative_solver_mod.f90
                            cg_solver_mod.f90
                            jacobi_mod.f90
                            bjacobi_mod.f90
                            ilu_mod.f90
                            linear_algebra_mod.f90""")

libs_for_linalg = Split("""blas lapack gomp""")

#linalgobjs = env.Object(linalg_sources)

linalglib = env.Library('linalg',linalg_sources,LIBS=libs_for_linalg)

#env.Alias('install', env.Install('../../lib',linalglib))

