#!/usr/bin/env python

Import('masterEnv')
env = masterEnv.Clone(F90FLAGS='-fbounds-check -g')

linalg_sources = Split("""sparse_matrix_mod.f90 
                            csr_matrix_mod.f90
                            permutation_mod.f90
                            iterative_solver_mod.f90
                            cg_solver_mod.f90
                            nullpc_mod.f90
                            jacobi_mod.f90
                            ilu_mod.f90
                            linear_algebra_mod.f90""")

linalgobjs = env.Object(linalg_sources)

linalglib = env.Library('linalg',linalg_sources)

#env.Alias('install', env.Install('../../lib',linalglib))

